### ISSUE TITLE
In case of error during rendering of the view in another module, its layout is not rendered

### ISSUE THREAD

**Issue by ghost** [njcom/framework#321]
Instead of rendering the module's layout the layout of system module is rendered.
Expected result: layout of the module where the error is occurred must be rendered.

**Comment by markbook2** [comment]
Add new test module, probably after introducing the VFS. Test this case: create a new foo.phtml file and throw an Exception there, it must be not inside the `system` module.

**Comment by jackstr** [comment]
Not actual anymore.
